# Copyright Advanced Micro Devices, Inc.
#
# SPDX-License-Identifier: MIT

subdir-ccflags-y := -include $(src)/../dkms/config.h
subdir-ccflags-y += -I$(src)/../inc

amd-vfio-pci-y += amd-vfio.o

obj-m += amd-vfio-pci.o
