# Copyright Advanced Micro Devices, Inc.
#
# SPDX-License-Identifier: MIT

LIBGV_PATH = $(src)/../libgv
GIM_SHIM_PATH = $(src)/gim_shim

SMI_LIB_PATH=$(src)/../smi-lib
SMI_DRV_PATH = $(SMI_LIB_PATH)/drv

GIM_COMS_PATH = $(src)/../gim-coms-lib

subdir-ccflags-y += -I$(GIM_SHIM_PATH) -I$(GIM_SHIM_PATH)/sysfs
subdir-ccflags-y += -I$(SMI_DRV_PATH)/inc -I$(SMI_DRV_PATH)/linux -I$(SMI_LIB_PATH)/inc/common
subdir-ccflags-y += -I$(GIM_COMS_PATH)/inc
subdir-ccflags-y += -I$(src)/inc
subdir-ccflags-y += -include $(src)/dkms/config.h
subdir-ccflags-y += -Wimplicit-fallthrough=2 -Wno-enum-conversion -Wno-expansion-to-defined
subdir-ccflags-y += -DAMDGV_UNIRAS_SUPPORT
subdir-ccflags-y += -DSHIM_LAYER_OSS_RADIX_TREE -DSHIM_LAYER_OSS_KFIFO -DSHIM_LAYER_OSS_MEMPOOL

# Ensure RAS portable-container objects always see shim flags (some kbuild paths
# omit global subdir-ccflags-y for ../uniras/ras/ sources).
CFLAGS_amdgv_ras_mempool.o += -DSHIM_LAYER_OSS_MEMPOOL
CFLAGS_amdgv_ras_fifo.o += -DSHIM_LAYER_OSS_KFIFO

include $(GIM_SHIM_PATH)/Kbuild

include $(LIBGV_PATH)/Makefile
gim-y += $(addprefix ../libgv/,$(LIBGV_COMPILE_FILES))
subdir-ccflags-y += $(LIBGV_CCFLAGS)

gim-y += $(patsubst uniras/ras/%,../uniras/ras/%,$(AMD_GPU_RAS_FILES))

include $(SMI_DRV_PATH)/Makefile
gim-y += $(addprefix ../smi-lib/drv/,$(SMI_COMPILE_FILES))

obj-m += amd-vfio-pci/
obj-m += gim.o
